export const UPDATEFS_REQUEST = "UPDATEFS_REQUEST";
export const UPDATEFS_SUCCESS = "UPDATEFS_SUCCESS";
export const UPDATEFS_FAILURE = "UPDATEFS_FAILURE";

export const UPDATEREGISTRATION_REQUEST = "UPDATEREGISTRATION_REQUEST";
export const UPDATEREGISTRATION_SUCCESS = "UPDATEREGISTRATION_SUCCESS";
export const UPDATEREGISTRATION_FAILURE = "UPDATEREGISTRATION_FAILURE";

export const GETBYCODE_REQUEST = "GETBYCODE_REQUEST";
export const GETBYCODE_SUCCESS = "GETBYCODE_SUCCESS";
export const GETBYCODE_FAILURE = "GETBYCODE_FAILURE";

export const REPORT_REQUEST = "REPORT_REQUEST";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAILURE = "REPORT_FAILURE";

export const COUNT_INSCRIT_REQUEST = "COUNT_INSCRIT_REQUEST";
export const COUNT_INSCRIT_SUCCESS = "COUNT_INSCRIT_SUCCESS";
export const COUNT_INSCRIT_FAILURE = "COUNT_INSCRIT_FAILURE";

export const STATISTIC_REQUEST = "STATISTIC_REQUEST";
export const STATISTIC_SUCCESS = "STATISTIC_SUCCESS";
export const STATISTIC_FAILURE = "STATISTIC_FAILURE";

export const SEND_MAIL_REQUEST = "SEND_MAIL_REQUEST"
export const SEND_MAIL_SUCCESS  = "SEND_MAIL_SUCCESS "
export const SEND_MAIL_FAILURE = "SEND_MAIL_FAILURE"

export const VERIF_CODE_REQUEST = "VERIF_CODE_REQUEST"
export const VERIF_CODE_SUCCESS  = "VERIF_CODE_SUCCESS "
export const VERIF_CODE_FAILURE = "VERIF_CODE_FAILURE"

export const ADD_CITIZEN_WITH_CIN_REQUEST = "ADD_CITIZEN_WITH_CIN_REQUEST";
export const ADD_CITIZEN_WITH_CIN_SUCCESS = "ADD_CITIZEN_WITH_CIN_SUCCESS";
export const ADD_CITIZEN_WITH_CIN_FAILURE = "ADD_CITIZEN_WITH_CIN_FAILURE";

export const ADD_ON_PHARMACY_REQUEST = "ADD_ON_PHARMACY_REQUEST";
export const ADD_ON_PHARMACY_SUCCESS = "ADD_ON_PHARMACY_SUCCESS";
export const ADD_ON_PHARMACY_FAILURE = "ADD_ON_PHARMACY_FAILURE";

export const RESET = "RESET";