export const VACCIN_NUMBER_REQUEST = " VACCIN_NUMBER_REQUEST";
export const  VACCIN_NUMBER_SUCCESS = " VACCIN_NUMBER_SUCCESS";
export const  VACCIN_NUMBER_FAILURE = " VACCIN_NUMBER_FAILURE";


export const DIABETIC_NUMBER_REQUEST = " DIABETIC_NUMBER_REQUEST";
export const DIABETIC_NUMBER_SUCCESS = " DIABETIC_NUMBER_SUCCESS";
export const DIABETIC_NUMBER_FAILURE = " DIABETIC_NUMBER_FAILURE";

export const BLOODPRESSURE_NUMBER_REQUEST = " BLOODPRESSURE_NUMBER_REQUEST";
export const BLOODPRESSURE_NUMBER_SUCCESS = " BLOODPRESSURE_NUMBER_SUCCESS";
export const BLOODPRESSURE_NUMBER_FAILURE = " BLOODPRESSURE_NUMBER_FAILURE";


export const CHRONICKIDNEYDISEASE_NUMBER_REQUEST = "CHRONICKIDNEYDISEASE_NUMBER_REQUEST";
export const CHRONICKIDNEYDISEASE_NUMBER_SUCCESS = " CHRONICKIDNEYDISEASE_NUMBER_SUCCESS";
export const CHRONICKIDNEYDISEASE_NUMBER_FAILURE = " CHRONICKIDNEYDISEASE_NUMBER_FAILURE";



export const CONGESTIVE_NUMBER_REQUEST = "CONGESTIVE_NUMBER_REQUEST";
export const CONGESTIVE_NUMBER_SUCCESS = "CONGESTIVE_NUMBER_SUCCESS";
export const CONGESTIVE_NUMBER_FAILURE = "CONGESTIVE_NUMBER_FAILURE";


