export const FETCH_PHARMACY_REQUEST = "FETCH_PHARMACY_REQUEST";
export const FETCH_PHARMACY_SUCCESS = "FETCH_PHARMACY_SUCCESS";
export const FETCH_PHARMACY_FAILURE = "FETCH_PHARMACY_FAILURE";

export const DELETE_PHARMACY = "DELETE_PHARMACY";

export const UPDATE_PHARMACY = "UPDATE_PHARMACY";

export const ADD_PHARMACY = "ADD_PHARMACY";

export const RESET = "RESET";