export const GET_VACCINES_REQUEST = "GET_VACCINES_REQUEST";
export const GET_VACCINES_SUCCESS = "GET_VACCINES_SUCCESS";
export const GET_VACCINES_FAILURE = "GET_VACCINES_FAILURE";

export const GET_VACCINE_BY_ID_REQUEST = "GET_VACCINE_BY_ID_REQUEST";
export const GET_VACCINE_BY_ID_SUCCESS = "GET_VACCINE_BY_ID_SUCCESS";
export const GET_VACCINE_BY_ID_FAILURE = "GET_VACCINE_BY_ID_FAILURE";

export const ADD_VACCINE_REQUEST = "ADD_VACCINE_REQUEST";
export const ADD_VACCINE_SUCCESS = "ADD_VACCINE_SUCCESS";
export const ADD_VACCINE_FAILURE = "ADD_VACCINE_FAILURE";

export const UPDATE_VACCINE_REQUEST = "UPDATE_VACCINE_REQUEST";
export const UPDATE_VACCINE_SUCCESS = "UPDATE_VACCINE_SUCCESS";
export const UPDATE_VACCINE_FAILURE = "UPDATE_VACCINE_FAILURE";

export const DELETE_VACCINE = "DELETE_VACCINE";

