export const FETCH_LIST_REQUEST = "FETCH_LIST_REQUEST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE";

export const DELETE_CENTER = "DELETE_CENTER";

export const UPDATE_CENTER = "UPDATE_CENTER";

export const ADD_CENTER = "ADD_CENTER";

export const RESET = "RESET";
export const RESET_ACTION = "RESET_ACTION";

export const ASSIGN_VACCINE_CENTER_REQUEST = "ASSIGN_VACCINE_CENTER_REQUEST";
export const ASSIGN_VACCINE_CENTER_SUCCESS = "ASSIGN_VACCINE_CENTER_SUCCESS";
export const ASSIGN_VACCINE_CENTER_FAILURE = "ASSIGN_VACCINE_CENTER_FAILURE";


export const AFFECT= "AFFECT";


