export const VALIDATION_FIXE_REQUEST = "VALIDATION_FIXE_REQUEST";
export const VALIDATION_FIXE_SUCCESS = "VALIDATION_FIXE_SUCCESS";
export const VALIDATION_FIXE_FAILURE = "VALIDATION_FIXE_FAILURE";


export const VALIDATION_MOBILE_REQUEST = "VALIDATION_FMOBILE_REQUEST";
export const VALIDATION_MOBILE_SUCCESS = "VALIDATION_MOBILE_SUCCESS";
export const VALIDATION_MOBILE_FAILURE = "VALIDATION_MOBILE_FAILURE";


export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILURE = "VERIFICATION_FAILURE";


export const RESET = "RESET";