export const FETCH_LIST_VOLUNTEER_REQUEST = "FETCH_LIST_VOLUNTEER_REQUEST";
export const FETCH_LIST_VOLUNTEER_SUCCESS = "FETCH_LIST_VOLUNTEER_SUCCESS";
export const FETCH_LIST_VOLUNTEER_FAILURE = "FETCH_LIST_VOLUNTEER_FAILURE";

export const DELETE_VOLUNTEER = "DELETE_VOLUNTEER";

export const UPDATE_VOLUNTEER = "UPDATE_VOLUNTEER";

export const ADD_VOLUNTEER = "ADD_VOLUNTEER";

export const RESET_VOLUNTEER = "RESET_VOLUNTEER";

